# Generated by Django 5.0.6 on 2024-07-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='numbers_of_products',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
