# Generated by Django 5.0.6 on 2024-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_brand_numbers_of_products_alter_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
