# Generated by Django 5.0.6 on 2025-02-10 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
